# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Ubuntu Version
        run: cat /etc/lsb-release
      - name: Python Version
        run: python3 --version
      - name: Setup Virtual Environment
        run: |
          source ./venv.bash
      - name: Tox - Tests [py38]
        # fast this time around since the last step did the installation, venv.bash will only check here
        run: |
          source ./venv.bash
          tox -e py38
      - name: Tox - Code and Doc Style [flake8]
        run: |
          source ./venv.bash
          tox -e flake8

      # Runs a single command using the runners shell
      - name: Froody
        run: echo I am froody, you should be too
