# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  # Attach tarballs to releases with stable release url's
  #   NB: tag url's aren't guaranteed to be persistent
  #   See: https://blog.bazel.build/2023/02/15/github-archive-checksum.html
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        run: |
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITUB_REF_NAME: ${GITHUB_REF_NAME}"
      - name: Env Variables
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "TARBALL_NAME=${{ env.REPO_NAME }}-${{ env.TAG }}.tar.gz" >> $GITHUB_ENV
      - name: Create Release Asset
        run: git archive $GITHUB_REF -o "${{ env.TARBALL_NAME }}"
      - name: Cut a Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files: ${{ env.TARBALL_NAME }}
